include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    deprecated_member_use: ignore
    unused_element: ignore
    unused_field: ignore
    unused_import: ignore
    use_build_context_synchronously: ignore
